QubesOS/qubes-core-qrexec

agent/qrexec-agent-data.c
agent/qrexec-agent.c
agent/qrexec-client-vm.c
daemon/Makefile
daemon/qrexec-client.c
daemon/qrexec-daemon.c
libqrexec/libqrexec-utils.h
libqrexec/qrexec.h
libqrexec/write-stdin.c

- Increase data chunk size to 64k.
- Increase allowed length of requested qrexec service name - MSG_TRIGGER_SERVICE message. 
Fixes https://github.com/QubesOS/qubes-issues/issues/4909

Protocol changes for R4.1

---

daemon/qrexec-daemon.c

Do not exit when qrexec-agent disconnects, instead try to reconnect.
This allows to restart qrexec-agent inside a VM (almost) without bad
consequences.
Since established qrexec connections are handled in separate processes,
those are not interrupted by such restart. But qrexec-agent loose
track of them. This means two things:
- ports used by such connections are never released (qrexec-daemon
intentionally keep them marked as busy)
- if anone waits for qrexec connection end notification, it will
receive it prematurely - on qrexec-agent restart; this may cause DispVM
to be prematurely killed
Fixes QubesOS/qubes-issues#1148

dom0: when qrexec-agent disconnects, try to reconnect

---

lib/qubes-rpc-multiplexer
libqrexec/exec.c
libqrexec/qrexec.h
qrexec/tests/socket/agent.py
qrexec/tests/socket/daemon.py

This is on top of QubesOS/qubes-core-qrexec#3. Main part is in 36ef73421484.

Socket based qrexec: refactor file search, add tests

---

agent/qrexec-agent-data.c
agent/qrexec-agent.h
agent/qrexec-client-vm.c
daemon/qrexec-client.c
libqrexec/Makefile
libqrexec/exec.c
libqrexec/libqrexec-utils.h
libqrexec/process_io.c
libqrexec/remote.c
libqrexec/replace.c
libqrexec/txrx-vchan.c
qrexec/tests/socket/agent.py
qrexec/tests/socket/daemon.py

What remains is the main loop; for now it's pretty different in both versions.

Common main loop for agent and client

---

.gitignore
agent/qrexec-agent-data.c
agent/qrexec-agent.c
agent/qrexec-agent.h
agent/qrexec-client-vm.c
daemon/qrexec-client.c
lib/qubes-rpc-multiplexer
libqrexec/Makefile
libqrexec/exec.c
libqrexec/libqrexec-utils.h
libqrexec/process_io.c
libqrexec/remote.c
libqrexec/replace.c
libqrexec/txrx-vchan.c
qrexec/tests/socket/agent.py
qrexec/tests/socket/daemon.py
qrexec/tools/qrexec_policy_daemon.py
systemd/qubes-qrexec-policy-daemon.service

Result of debugging session together with @pwmarcz
May fix QubesOS/qubes-issues#5597

Various fixes for socket handling corner cases

---

agent/qrexec-agent-data.c

qrexec-fork-server receives a command line without username at the
beginning. This was handled for MSG_EXEC_CMDLINE (see
execute_qubes_rpc_command in exec.c) but not for MSG_JUST_EXEC.

Fix qrexec-fork-server handling of MSG_JUST_EXEC

---

libqrexec/process_io.c

The client code complains when we run with local process, and the
service closes vchan before that process exits. This can be
observed sometimes when running dnf in a VM, when it notifies dom0
about updates:
process_io.c:181:process_io: vchan connection closed early
(fds: -1 -1 -1, status: -1 126)
However, this behaviour is completely legitimate and in fact the
code handles it (there is a waitpid() after the loop). The code is
messy and demands more attention, but for now, silence this case
so that there is no false positive.

Remove false error message on vchan disconnect

---

Documentation/qubes-policy.rst
qrexec/policy/parser.py
qrexec/tests/policy_parser.py

Requires internal API modification
(PR: QubesOS/qubes-core-admin#361).
See QubesOS/qubes-issues#5952.

Add 'autostart=no' option to policy

---

agent/qrexec-agent.c
daemon/qrexec-daemon.c
qrexec/tests/socket/daemon.py

See indiviual commit messages for details
Fixes QubesOS/qubes-issues#6120

Fix qrexec-agent crashing with "pselect: Bad file descriptor"

---

Makefile
agent/Makefile
agent/qrexec-agent.c
qrexec/tools/qrexec_policy_exec.py

Allow to build w/o pam

---

daemon/qrexec-daemon.c

Otherwise we get linker errors.

Link with -lgcov when building with coverage

---

agent/qrexec-client-vm.c

This avoids undefined behavior if we get an absurdly large buffer size
value.

Be stricter about command-line parsing

---

ci/requirements.txt
qrexec/__init__.py
qrexec/tests/cli.py
qrexec/tests/gtkhelpers.py
qrexec/tests/qrexec_policy_daemon.py
qrexec/tests/rpcconfirmation.py
qrexec/tools/qrexec_policy_agent.py
qrexec/tools/qrexec_policy_daemon.py
qrexec/tools/qrexec_policy_exec.py
qrexec/tools/qrexec_policy_restore.py
run-tests

The current implementation is naive, but a faster one is certainly
possible.

Add a policy.Eval qrexec service

---

.pylintrc
qrexec/client.py
qrexec/exc.py
qrexec/policy/admin.py
qrexec/policy/parser.py
qrexec/server.py
qrexec/tools/qrexec_policy_agent.py
qrexec/tools/qrexec_policy_daemon.py
qrexec/tools/qrexec_policy_exec.py
qrexec/tools/qrexec_policy_graph.py
qrexec/utils.py

Wrap coroutine in a task before passing to asyncio.wait

---

daemon/qrexec-daemon.c
fuzz/Makefile
fuzz/fuzz.c
fuzz/fuzz.h
fuzz/gen-seed-corpus
fuzz/mock-fuzz.h
fuzz/qrexec_daemon_fuzzer.c
fuzz/qrexec_remote_fuzzer.c
fuzz/qubesrpc_parse_fuzzer.c

This will allow finding bugs like QSB-089 in the future.

Add fuzzing handle_message_from_agent()

---

debian/qubes-core-qrexec.install
qrexec/tools/qubes_policy_editor.py
qrexec/tools/qubes_policy_lint.py
rpm_spec/qubes-qrexec.spec.in

Discussed previously in the mailing list.

Add lint and editor policy tools

---

agent/qrexec-agent-data.c

If remote VM fails to establish (already allowed by the policy)
connection, the local side (qrexec-client-vm) will wait indefinitely.
Similarly, if the calling side (qrexec-client-vm) do not finish
connection setup (gets killed early? or maybe the whole VM goes down?),
there will be a process waiting on the remote side (either
qrexec-fork-server child, or qrexec-agent child).
Solve this issue by adding connection timeout similar to what
qrexec-client (in dom0) does. Since both libvchan_server_init() and
libvchan_client_init() are involved, add new function that can handle
both.
This code is shared between qrexec-client-vm and qrexec-fork-server, so
both are covered.
Fixes QubesOS/qubes-issues#8476

Add connection timeout on the VM side too

---

rpm_spec/qubes-qrexec.spec.in

https://github.com/QubesOS/qubes-issues/issues/8499

Support for Fedora 39

---

debian/control
rpm_spec/qubes-qrexec.spec.in

Fixes: https://github.com/QubesOS/qubes-issues/issues/8644

Add missing dependency inotify

---

qrexec/tests/policy_graph.py
qrexec/tools/qrexec_policy_graph.py
rpm_spec/qubes-qrexec.spec.in

Fixes https://github.com/QubesOS/qubes-issues/issues/8648

Fixes to qrexec-policy-graph

---

.gitlab-ci.yml
agent/qrexec-agent.c
daemon/qrexec-daemon.c
libqrexec/exec.c
libqrexec/libqrexec-utils.h
libqrexec/process_io.c
libqrexec/qrexec.h
qrexec/tests/socket/agent.py
qrexec/tests/socket/daemon.py
qrexec/tests/socket/qrexec.py

Only IP addresses are supported.  This is based on #139.

TCP connection support

---

qubes-rpc-config/README

Fixes: https://github.com/QubesOS/qubes-issues/issues/9036
See comment https://github.com/QubesOS/qubes-issues/issues/9036#issuecomment-2083760576

Document rpc-config until skip-service-descriptor

---

daemon/qrexec-daemon.c

This makes things faster and trivially more correct.

qrexec-daemon: Use close_range where possible

---

daemon/qrexec-daemon-common.h
doc/execution.rst
doc/index.rst
libqrexec/libqrexec-utils.h

I plan on keeping this in this repository, rather than in the docs repo, for maintenance reasons.
Also fix a memory leak and refactor the code to make it easier to document.
Based on #140.

Documentation

---

qrexec/tools/qrexec_policy_agent.py

references QubesOS/qubes-issues#9195

Remove deprecated pkg_resources, replace with importlib

---

agent/qrexec-client-vm.c

Cherry picked the help message from `qrexec-client`.

qrexec-client-vm: fix missing option in usage and reorder it

---

daemon/qrexec-daemon-common.c
daemon/qrexec-daemon.c

Especially log errno when relevant

daemon: log a bit more info on errors

---

qrexec/policy/admin.py
qrexec/tests/policy_admin.py

Improves: https://github.com/QubesOS/qubes-issues/issues/8795

Provide clear error on invalid policy file name

---

qrexec/tests/qrexec_policy_daemon.py
qrexec/tools/qrexec_policy_daemon.py

Fix tests that are missing mock of get_system_info and fix uncovered problems

---

qrexec/policy/parser.py
qrexec/tests/policy_parser.py

See individual commit messages.

 qrexec/tests/policy_parser cleanup

---

archlinux/PKGBUILD.install

Add the restart on archlinux too.
Fixes: 27facce "Restart qrexec-agent on update"

archlinux: restart qubes-qrexec-agent on update
