QubesOS/qubes-core-qrexec

- agent/qrexec-agent-data.c
- agent/qrexec-agent.h
- agent/qrexec-client-vm.c
And enable it by default when stdout/stderr is connected to terminal.
Fixes QubesOS/qubes-issues#5322
> qrexec-client-vm: add option to replace control characters on stdout/err

- daemon/qrexec-client.c
This caused qrexec-client to be killed when the local process
exited (by design) before consuming all the input, for instance
when receiving too much data for the admin.vm.volume.Import call.
> qrexec-client: ignore SIGPIPE

- qrexec/tests/gtkhelpers.py
- qrexec/tests/rpcconfirmation.py
The tests for GTK objects used multiple inheritance to combine
TestCase class and the class being tested. This made the code more
confusing, but also caused the GTK objects to be initialized when
loading (not executing) the test, which can cause a segfault if
X is not available.
I rewrote the tests to use composition instead of inheritance,
creating an object (self.window, etc.) in the setUp method.
> Separate GTK test classes from object under test

- agent/qrexec-agent.c
We need the PAM setup to initialize environment for user session,
even if we do not actually change the user. Keep the simplified
behaviour to tests.
> agent: don't skip PAM setup outside of tests

- daemon/qrexec-daemon.c
Should prevent the situations where a wrong vchan connection is
terminated, which causes e.g. premature termination of a DispVM.
See longer discussion in QubesOS/qubes-issues#3318.
> daemon: prevent collisions between port numbers

- .travis.yml
- Documentation/qrexec-policy-daemon.rst
- Makefile
- ci/requirements.txt
- daemon/qrexec-daemon.c
- debian/qubes-core-qrexec.install
- qrexec/__init__.py
- qrexec/policy/parser.py
- qrexec/policy/utils.py
- qrexec/tests/cli.py
- qrexec/tests/policy_cache.py
- qrexec/tests/policy_parser.py
- qrexec/tests/qrexec_policy_daemon.py
- qrexec/tools/qrexec_policy_daemon.py
- qrexec/tools/qrexec_policy_exec.py
- rpm_spec/qubes-qrexec-dom0.spec.in
- rpm_spec/qubes-qrexec.spec.in
- systemd/qubes-qrexec-policy-daemon.service
Rewritten qrexec-daemon to use policy daemon instead of running
policy-exec separately for each call. If daemon fails, falls back
to old solution. Also contains some tests.
fixes QubesOS/qubes-issues#5125
> Qrexec policy daemon

- .gitignore
- .travis.yml
- agent/qrexec-agent.c
- ci/Dockerfile
- daemon/qrexec-daemon.c
- qrexec/tests/socket/daemon.py
- run-tests
On top of #22.
- The daemon might receive SIGTERM while reconnecting. There is no
simple way of interrupting the reconnection, so just allow it to
die.
- In the above case, dump coverage data (if running in tests) to
ensure SIGTERM doesn't wipe it.
- Close vchan on exit: also important for tests (to flush remaning
data to socket).
>  daemon, agent: ensure proper shutdown

- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- agent/qrexec-agent.h
- agent/qrexec-client-vm.c
- agent/qrexec-fork-server.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon.c
- libqrexec/Makefile
- libqrexec/buffer.c
- libqrexec/exec.c
- libqrexec/ioall.c
- libqrexec/libqrexec-utils.h
- libqrexec/log.c
- libqrexec/process_io.c
- libqrexec/remote.c
- libqrexec/txrx-vchan.c
- libqrexec/unix-server.c
- libqrexec/write-stdin.c
- Unify (fprintf/perror/fputs)
- Add context info (source, timestamp, PID)
- Log levels are not used yet, but they're there in case we want to silence something later
As a next step, I would add more "info" level messages to qrexec-agent and daemon, so that we know what request failed, not only how.
> Clean up error logging

- agent/qrexec-agent.c
- daemon/qrexec-daemon.c
- libqrexec/libqrexec-utils.h
- libqrexec/txrx-vchan.c
Use a pselect() in the main loop, unblocking the signals during
waiting, same as in process_io().
Still handle incoming vchan messages when outgoing vchan is blocked
(libvchan_buffer_space() too low). This was the case for agent, but
not for daemon.
Create a pselect_vchan() function that handles vchan quirks, but is
closer in semantics to regular pselect().
> daemon, agent: unify main loop

- fuzz/Makefile
As required by oss-fuzz:
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Requirements
> fuzzer: use C++ compiler for linking

- qrexec/policy/utils.py
rm_watch() accepts a list, but not arbitrary iterable. Convert
`dict_values` to `list`.
> policy/utils: fix pyinotify cleanup

- daemon/qrexec-client.c
- qrexec/tests/socket/daemon.py
Otherwise, qrexec-client just hangs when it fails to spawn a
process, or connect to a socket service.
This corresponds to the fix for qrexec-agent in commit
95fa4bb2d29fcfc91da3ada95300258450022610.
> qrexec-client: handle failed service exec

- agent/qrexec-agent.c
- daemon/qrexec-daemon.c
This is necessary because we block SIGCHLD at the beginning of the
main loop. The child will execute other commands that might depend
on SIGCHLD (in our case, this broke qrexec-policy-exec).
> qrexec-agent, qrexec-daemon: unblock signals before exec()

- Documentation/qubes-policy.rst
- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
Meaning all possible VMs, including dom0.
See QubesOS/qubes-issues#5953.
> policy: allow '*' as source and target

- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
If the requested target does not exist, interpret it as it wasn't provided
at all. This prevents the source domain learning if a given target exists
when the policy is set to default `ask` action
(`... @anyvm ask`). In such a case, previous behavior differed based on 
target existence: if it did exist, the user get a prompt, otherwise the 
request is immediately refused.
Note it is still possible to write a policy that allows the source to 
confirm/deny existence of arbitrary domain (for example default `allow` 
action, or denying only `@default` target). But such policy would need to
be specifically configured, it does no longer apply to default
(innocently-looking) policy.
Fixes QubesOS/qubes-issues#5955
> policy: interpret invalid requested target as @default

- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
default_target needs to have keywords expanded before passing to the
confirmation prompt. Otherwise default_target may not match any allowed
targets. That's the case for at least @dispvm and @adminvm.
Fixes QubesOS/qubes-issues#6112
> Fix handling default_target in ask action

- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
Similarly to 'ask' default_target parameter, expand actual 'target'
parameter in case of allow action (explicit or implicit via ask). This
makes the '@adminvm' keyword isolated to the policy internal logic, but
when communicating externally, it gets translated to the actual VM name
(which currently always is 'dom0', but may be translated into "local
AdminVM" in the future).
QubesOS/qubes-issues#6112
> policy: adjust call target for allow action too

- daemon/qrexec-daemon.c
- libqrexec/exec.c
- qrexec/tests/socket/agent.py
- qrexec/tests/socket/daemon.py
- qrexec/tools/qrexec_policy_agent.py
- qubes-rpc-dom0/qubes.WaitForSession
- systemd/qubes-qrexec-agent.service
When service call request arrives, qrexec-daemon spawns separate process
for evaluate the qrexec policy and call back for connection setup via
qrexec-client (if allowed). Since QubesOS/qubes-issues#6120 fix,
qrexec-daemon verifies if the request ident from qrexec-client really
was requested by qrexec-agent and is pending response (avoid responding
twice to the same request). It basically works like this:
1. qrexec-agent sends connection request (with ident X)
2. qrexec-daemon spawns a process for policy evaluation, and save its
PID associated with request ident (X), plus info that response is
pending - in a "policy_pending" array
3. policy gets evaluated and when accepted, qrexec-client is called to
setup the connection
4. qrexec-client connects back to qrexec-daemon, sending ident X + …
> daemon: fix handling multiple parallel qrexec-policy processes

- systemd/qubes-qrexec-agent.service
Restart only the main process, do not kill children (responsible for
passing data for established connections). This fixes installing updates
(when qrexec is updated too) using Salt or other qrexec service.
QubesOS/qubes-issues#1148
> agent: do not interrupt established connections on restart

- qrexec/policy/parser.py
Otherwise we assert when trying to launch the DispVM.  The assertion is
still useful to catch bugs elsewhere in the system.
Fixes QubesOS/qubes-issues#6629.
> Create a DispVMTemplate instance when needed

- lib/qrexec-policy-agent-autostart
... instead of specific guivm-gui-agent.
QubesOS/qubes-issues#4186
> Use generic 'guivm' service to tell if running inside GUI VM

- daemon/qrexec-daemon.c
The qrexec-daemon's child process that talks to the policy daemon was
holding various FD open. They were closed only if communication with the
policy daemon failed, before going to the fallback option of direct
qrexec-policy-exec call. Some of those FDs were used to notify then a
qrexec connection was terminated - by closing it. When they were leaked,
there always was some process keeping them open, so notification
was not delivered.
Fixes QubesOS/qubes-issues#6695
Fixes QubesOS/qubes-issues#6649
> Fix FD leak causing DispVMs not being cleaned up properly

- agent/qrexec-agent.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon.c
- libqrexec/txrx-vchan.c
Using FD_SET with a file descriptor not less than FD_SETSIZE is
undefined behavior.
Draft because not tested yet.
> Add assertions that FD_SETSIZE is not exceeded

- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
Report it as proper failed call exception, so that policy-daemon will
report it back properly as refused call. Otherwise qrexec-client will
fallback to a direct qrexec-policy-exec call. This would cause second
(unexpected) start try.
Fixes QubesOS/qubes-issues#7031
> policy: fix reporting failed target start

- agent/qrexec-agent.c
It will fail if the output buffer is too small or if the implementation tries and fails to allocate heap memory.
> Check the return value of snprintf

- daemon/qrexec-daemon.c
If no port can be allocated, allocate_vchan_port() should return 0, not
-1.
Fixes QubesOS/qubes-issues#7201
> Fix error return value in allocate_vchan_port

- qrexec/policy/parser.py
- fill the call target in the message
- consider 'notify=yes'/'notify=no' when showing the message
Reported by @adrelanos
Fixes QubesOS/qubes-issues#7267
> policy: fix notification on refused autostart

- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
Policy files in /etc/qubes-rpc/policy use coma to separate action from
parameters, not only between parameters. Fix that.
Fixes QubesOS/qubes-issues#7122
> Fix parsing legacy policy files

- rpm_spec/qubes-qrexec-dom0.spec.in
Now it's owned by qubes group, not root group,
to enable editing policy by normal system tools.
fixes QubesOS/qubes-issues#7604
> Fix incorrect ownership of policy dirs

- archlinux/PKGBUILD
Should not break CI.
Sidenode: the Arch Linux template I downloaded long ago seem to have not have package registry setup correctly (the files are installed, but the packages like `qubes-vm-qrexec` are not seen as installed to pacman.
> In PKGBUILD: copy instead of symlink

- Makefile
- policy.d/90-admin-policy-default.policy
- qrexec/client.py
- qrexec/policy/admin.py
- qrexec/policy/admin_client.py
- qrexec/policy/parser.py
- qrexec/policy/parser_compat.py
- qrexec/tests/policy_admin.py
- qrexec/tests/policy_parser.py
- rpm_spec/qubes-qrexec-dom0.spec.in
Needed for global configuration tool.
Also removed requirement for root for performing policy queries, added str representation for policy rules and renamed TestPolicyLoaders to StringPolicyLoaders to be able to use them more flexibly.
> Add a new get_files method to policy admin api

- libqrexec/remote.c
Since they are handled the same way, do not ignore remote side sending
the wrong one, just warn about it (once). QWT have it mixed up, so
ignoring such messages breaks communication with QWT.
Fixes QubesOS/qubes-issues#7917
> Relax validation of MSG_DATA_STDIN/MSG_DATA_STDOUT

- agent/qrexec-agent-data.c
- agent/qrexec-agent.h
- agent/qrexec-client-vm.c
- daemon/qrexec-client.c
- libqrexec/libqrexec-utils.h
- libqrexec/process_io.c
- libqrexec/remote.c
This allows passing a prefix data argument to qrexec-client-vm.  Prefix
data is sent before the data on stdin, which is useful for e.g.
requesting armored or binary OpenPGP signatures.
> Prefix data support

- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon.c
- libqrexec/libqrexec-utils.h
- libqrexec/txrx-vchan.c
- libqrexec/write-stdin.c
This avoids select()’s FD_SETSIZE limit.  It has been broken up into several commits for ease of review, as a previous attempt to make the entire change at once turned out to be buggy.
> Switch from ‘select’ to ‘poll’

- libqrexec/process_io.c
- qrexec/tests/socket/agent.py
If the local process failed, the exit code must be non-zero.  Otherwise callers will believe that the local process succeeded when it did not. In the case of qvm-move and qvm-move-to-vm, the result is that the shell script wrapper deletes the source files even though some of them were not transferred to the destination qube.  This destroys user data.
Reported-by: Marta Marczykowska-Górecka <marmarta@invisiblethingslab.com>
Fixes: QubesOS/qubes-issues#7905
> Do not exit successfully if local process failed

- .gitignore
- Makefile
- agent/qrexec.pam
- rpm_spec/qubes-qrexec-vm.spec.in
- selinux/qubes-core-qrexec.fc
- selinux/qubes-core-qrexec.if
- selinux/qubes-core-qrexec.te
- systemd/qubes-qrexec-agent.service
This allows qrexec to run on systems with SELinux in enforcing mode.  Part of QubesOS/qubes-issues#4239.
~~Marked as draft because I have not tested it yet.  In particular, there might be problems with the packaging.~~ Tested and problems fixed.
> Add SELinux policy for qrexec

- qrexec/exc.py
- qrexec/policy/parser.py
- qrexec/tools/qrexec_policy_exec.py
- qrexec/utils.py
It isn't available in Python 3.6 (CentOS Stream 8), use manual string
annotations where necessary instead.
> Do not use 'annotation' future extension

- daemon/qrexec-daemon.c
- qrexec/tests/socket/daemon.py
Mangling the request ID is not useful: the agent will use the mangled request ID to look up the request, which is not going to work.  Instead, directly send MSG_SERVICE_REFUSED with the raw (unsanitized) request ID.
> Reject requests with invalid request ID

- agent/qrexec-agent.c
This ensures that an invalid message (with hdr.len == sizeof(params)) will not be sent to qrexec-daemon.  Starting with the QSB-089 fixes such a message will cause qrexec-daemon to terminate.
> Fix header validation by qrexec agent

- qrexec/utils.py
Debian uses Python 3.9.2 which does not support typing.TypeAlias. Ensure that typing.TypeAlias is only used when type checking.
> Support Debian 11

- Makefile
- agent/Makefile
- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- daemon/Makefile
- daemon/qrexec-daemon.c
- fuzz/fuzz.c
- fuzz/fuzz.h
- fuzz/qrexec_daemon_fuzzer.c
- libqrexec/Makefile
- libqrexec/log.c
- libqrexec/replace.c
They are deprecated in all versions of C and are fundamentally unsafe. Also ensure that all objects with external linkage are declared before being defined.
> Banish old-style function declarations

- daemon/qrexec-daemon.c
These variables are only used in that block, so declare them in that block.
> Move variables into MSG_TRIGGER_SERVICE3 block

- daemon/qrexec-daemon.c
A service name that contains a NUL byte is clearly bogus.  Reject the service call rather than truncating the service name.  Also reject service names that start with `+`, as this corresponds to the name of the service (rather than its argument) being the empty string.  I don’t think the new policy format can express this.
> Reject obviously bogus service names

- qubes-rpc-dom0/policy.RegisterArgument
Make it add rules into
/etc/qubes/policy.d/60-registered-arguments.policy, instead of legacy
/etc/qubes-rpc/policy.
Since the new format can have multiple rules in a single file, locking
is necessary. Do it the same way as other policy.* services, so it's
coordinated too.
QubesOS/qubes-issues#8000
> Make policy.RegisterArgument use new policy format

- agent/Makefile
- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- agent/qrexec-agent.h
- agent/qrexec-fork-server.c
- daemon/qrexec-client.c
- fuzz/Makefile
- libqrexec/Makefile
- libqrexec/exec.c
- libqrexec/libqrexec-utils.h
- libqrexec/remote.c
- libqrexec/toml.c
- qrexec/tests/socket/agent.py
This also dramatically improves the configuration parser.  Configuration files now use a strict subset of TOML rather than an ad-hoc format with no validation.
Fixes: QubesOS/qubes-issues#6354
Fixes: QubesOS/qubes-issues#8153
> Allow specifying a username in service config

- debian/qubes-core-qrexec.install
- qrexec/tests/qrexec_legacy_convert.py
- qrexec/tools/qrexec_legacy_convert.py
- qrexec/tools/qrexec_policy_graph.py
- rpm_spec/qubes-qrexec.spec.in
- setup.py
fixes QubesOS/qubes-issues#8000
> Add a tool to convert legacy policy files to new format

- libqrexec/process_io.c
This caused the process to hang.
Fixes: 3a93b65edd7bda908653aeeb9c43ab4aa906660a ("Prefix data support")
Fixes: QubesOS/qubes-issues#8628
> Don't wait for stdin if there is unsent prefix data

- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- daemon/qrexec-client.c
- libqrexec/Makefile
- libqrexec/buffer.c
- libqrexec/exec.c
- libqrexec/libqrexec-utils.h
- libqrexec/private.h
- libqrexec/toml.c
- qrexec/tests/socket/agent.py
- qrexec/tests/socket/daemon.py
- qrexec/tests/socket/qrexec.py
- run-tests
This makes it easier to implement socket-based services that do not
require the metadata.  This avoids having to use a slow executable-based
service or write a custom wrapper.
Fixes: https://github.com/QubesOS/qubes-issues/issues/9036
Edit: This PR now also fixes https://github.com/QubesOS/qubes-issues/issues/9073.  Furthermore, the first four commits fix multiple bugs in the test suite, and the fifth and sixth are purely test suite enhancements.
> Support not passing metadata to socket-based services

- agent/qrexec-agent.c
- agent/qrexec-client-vm.c
- daemon/Makefile
- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon-common.h
- daemon/qrexec-daemon.c
- doc/qrexec-policy-daemon.rst
- fuzz/Makefile
- libqrexec/exec.c
- libqrexec/ioall.c
- libqrexec/libqrexec-utils.h
- libqrexec/write-stdin.c
- qrexec/tests/socket/daemon.py
- qrexec/tests/socket/qrexec.py
This saves an `execve()`.  It also allows qrexec-daemon to change how it performs a VM -> VM service call without having to change qrexec-client.  During an upgrade, it is possible that qrexec-daemon is newer than qrexec-client, causing the new qrexec-daemon to try to use a calling convention that the old qrexec-client doesn't support.  Doing VM -> VM calls without calling execve() means this cannot happen.  VM -> dom0 and dom0 -> VM calls still use qrexec-client, but VM -> dom0 calls are safe from domain name reuse races as of 654635c2a374272f18bdfe59472a8ae6b51a551e, and the latter do not involve qrexec-daemon at all.
The preceding commits are all either cleanups or bug fixes.
> Avoid using qrexec-client for VM ⇒ VM calls

- qrexec/tests/socket/agent.py
Various tests assumed that qrexec would deliver stdout in a single message.  Qrexec does not make this guarantee: calls to write(2), send(2), sendmsg(2), etc are not guaranteed to correspond 1-to-1 to MSG_DATA_STDOUT messages on the vchan.  This caused https://gitlab.com/QubesOS/qubes-core-qrexec/-/jobs/6616564043 to wrongly fail, even thouggh the code is correct.
Fix this problem by concatenating the payloads of all stdout messages into a single bytes object before comparing with the expected stdout value.  Also add a utility function for this, saving a lot of code in tests.
> Fix flaky qrexec agent tests

- agent/qrexec-agent-data.c
- libqrexec/exec.c
- libqrexec/libqrexec-utils.h
- qrexec/tests/socket/agent.py
This separates _finding_ a qrexec service (and, if necessary, connecting to a socket) from actually _executing_ the service and processing I/O. This allows qrexec-agent to handle `MSG_JUST_EXEC` correctly, because it can connect to a socket-based service without having to be prepared for an executable service to be run immediately.  Instead, qrexec-agent spawns an executable service using its own spawning routines that do support `MSG_JUST_EXEC`.
This also adds tests for RPC services (both executable and socket) with `MSG_JUST_EXEC`.  Previously, these were not tested, despite being essential to a running system.  For instance, the Qubes app menu uses `MSG_JUST_EXEC` to invoke the qubes.StartApp service every time it launches an application in a non-disposable VM from dom0.
> Support socket services with `MSG_JUST_EXEC`

- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- agent/qrexec-fork-server.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon.c
- fuzz/Makefile
- fuzz/fuzz.c
- fuzz/fuzz.h
- fuzz/mock-fuzz.h
- libqrexec/Makefile
- libqrexec/libqrexec-utils.h
- libqrexec/qrexec.h
- libqrexec/unix-server.c
- libqrexec/vchan_timeout.c
libvchan has much better ways of dealing with timeouts now, so use them instead of calling an async signal unsafe function from a signal handler.  Both qrexec-agent-data.c and qrexec-daemon-common.c reimplemented timeouts, so write common code in libqrexec for both to use.
Based on #136 which is already approved.
> Avoid using alarm(2) for timeouts

- libqrexec/vchan_timeout.c
- qrexec/tests/socket/daemon.py
The other possible behavior (instantly failing the service call) is not useful.
Fixes: QubesOS/qubes-issues#9126
Fixes: c664954bf06a ("Avoid using alarm(2) for timeouts")
> Treat zero timeout as infinite

- agent/qrexec-client-vm.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon-common.h
- libqrexec/exec.c
- libqrexec/libqrexec-utils.h
- libqrexec/process_io.c
- qrexec/tests/socket/agent.py
use_stdio_socket means that stdin and stdout FDs use the same file description, which is certainly the case for socket-based services. Before this change, it was set to false in this case.  This would cause the file description to be made blocking while it is still in use, potentially causing deadlocks.
git blame points to commit 0802df70eefcf5f897b3782313d01bc1bbc3712b ("Factor out process_child_io"), but I suspect the actual bug dates back as far as the introduction of socket-based services in 76697e30f6e19bb003d669e5bdcb4dae739ac878 ("Working socket-based qrexec").
Fixes: QubesOS/qubes-issues#9169
> Do not make a file description blocking while it is still in use

- daemon/qrexec-daemon.c
Found by clang-tidy.  No tests, but the fix is trivial.
Fixes: 3d658cc82739 ("Use a pipe instead of signals to notify readiness")
> Avoid writing to an uninitialized file descriptor

- rpm_spec/qubes-qrexec-dom0.spec.in
- rpm_spec/qubes-qrexec-vm.spec.in
Old command line tools work with a new qrexec library so long as the library SONAME matches, but new command line tools will not work with an older library.  Add an explicit dependency to enforce ordering.
Fixes: QubesOS/qubes-issues#9184
> Ensure proper RPM dependency ordering

- libqrexec/process_io.c
- libqrexec/remote.h
When looking at the code I initially thought that commit
b8f0031285d87cbef9aad9902ef1fea9126ad960 introduced a use after free
vulnerability.  It does not, but this was not clear from reading the
code, so add comments to explain why the buffer (unlike stdin_buf) can
just be uninitialized memory and will always be valid throughout
process_io() until it is freed.
Also avoid allocating two buffers when one will do.
> Explain why no use after free

- daemon/qrexec-daemon.c
Save the log file in /var/log/qubes, instead of /run/qubes/ (or other
chosen socket directory).
This partially reverts 2901f00 "Make all paths relative to socket directory"
Fixes: 2901f00 "Make all paths relative to socket directory"
Fixes QubesOS/qubes-issues#9185
> Restore correct log path

- agent/Makefile
- daemon/Makefile
- libqrexec/Makefile
Leave it for the package builder to define, according to the policy of
specific distribution. And also, do not fight with provided environment,
try to play along instead - drop "override" and custom variables. This
also avoids including $(CFLAGS) twice. This rollback some of the changes
in b883dcb "Makefile improvements"
https://github.com/QubesOS/qubes-builder-archlinux/pull/73#issuecomment-2089227995
> Fix build error on redefined _FORTIFY_SOURCE

- libqrexec/process_io.c
- qrexec/tests/socket/agent.py
Just shut it down for writing, and save it so that it can later be used for reading.
This also ensures deterministic behavior when --use-stdin-socket is used.  Previously, the socket would be shut down for reading or writing but not both, depending on whether reading or writing stopped first. This could be quite confusing for callers.  Instead, always shut down the socket for both reading and writing, guaranteeing deterministic behavior.
Fixes: a3bbcb5f4314 ("Prefer close() to shutdown()")
Fixes: QubesOS/qubes-issues#9183
> Fix SIGUSR1 after stdin_fd closed

- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- agent/qrexec-agent.h
- agent/qrexec-client-vm.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon-common.h
- daemon/qrexec-daemon.c
- libqrexec/exec.c
- libqrexec/libqrexec-utils.h
- libqrexec/log.c
- libqrexec/private.h
- libqrexec/process_io.c
- libqrexec/toml.c
- qrexec/tests/socket/agent.py
- qrexec/tests/socket/qrexec.py
This adds two new boolean service configuration options:
- exit-on-stdout-eof: exit when the socket service shuts down its output stream for writing.
- exit-on-stdin-eof: exit when the client sends EOF.
To avoid compatibility problems, global variables are used to pass this information from the configuration parser to the I/O code.  In the future, there should be a better way to pass this information, but this is not possible without more extensive changes.  Fortunately, the configuration parser only runs once in the life of any process right now, so this commit adds assertions to check this.  Qubes OS ships with assertions enabled, so any violation of this rule will be detected.
The main use of these features is to emulate the old qubes.ConnectTCP and qubes.UpdatesProxy services, which …
> Add support for exiting on stdin or stdout EOF     

- qrexec/tools/qrexec_policy_exec.py
The case where process_id and domain_id are not set do result in earlier
return (due to no_exec=True).
> Mute pylint false positive

- qubes-rpc-config/README
For: https://github.com/QubesOS/qubes-issues/issues/9176
> Document rpc config until exit-on-server-eof

- daemon/qrexec-daemon-common.c
- libqrexec/process_io.c
- qrexec/tests/socket/agent.py
- qrexec/tests/socket/daemon.py
Previously, this was not guaranteed to happen if the process was exiting, and neither dom0 nor socket services would send a `MSG_DATA_STDERR`.
Fixes: QubesOS/qubes-issues#9142
Fixes: QubesOS/qubes-issues#9248
Fixes: QubesOS/qubes-issues#9249
> Always send EOF on streams

- libqrexec/exec.c
- qrexec/tests/socket/agent.py
If service type is changed from socket to executable, some config
options are not applicable anymore. Do not fail execution but just log a
warning. This is also relevant for migration in the other direction - if
user has an executable service that is updated to a socket service, user
may want preserve the executable variant (which is also done by the
package manager if user has modified said service) - in which case, the
config for socket variant should not prevent this configuration from
working.
This has been reported to happen with qubes.UpdatesProxy service.
Fixes QubesOS/qubes-issues#9299
> Downgrade errors about incompatible service config to warnings

- qrexec/tests/socket/agent.py
Previously the expected stdout was completely ignored.
> tests: Actually check that stdout was expected value

- qrexec/policy/utils.py
- qrexec/tests/policy_cache.py
Invalidate cache not only when file is modified inside policy dir, but
also when it's moved in or out.
> policy-daemon: invalidate cache on file move too

- qrexec/tools/qrexec_policy_agent.py
fixes: https://github.com/QubesOS/qubes-issues/issues/8583
> Support substring matching in qube name text fields

- daemon/qrexec-daemon.c
process_io() loop doesn't check flag set by SIGTERM handler in the parent
qrexec-daemon process. This results in child processes (for example
handling socket service calls to dom0) effectively ignore SIGTERM. This
subsequently cause system shutdown to wait (until finally sending SIGKILL).
Fix this by restoring default SIGTERM handler in the child process.
Fixes: f3a5784 "Avoid qrexec-client for VM -> dom0 calls"
> daemon: restore SIGTERM default handler in child process

- .pylintrc
- Makefile
- qrexec/__init__.py
- qrexec/policy/parser.py
- qrexec/policy/utils.py
- qrexec/tests/cli.py
- qrexec/tests/policy_cache.py
- qrexec/tools/qrexec_legacy_convert.py
- qrexec/tools/qrexec_policy_daemon.py
- qrexec/tools/qrexec_policy_exec.py
- rpm_spec/qubes-qrexec-dom0.spec.in
- systemd/qrexec.conf
This allows multiple directories to contain qrexec policy, which allows for transient policy that disappears on reboot.
Fixes: QubesOS/qubes-issues#8513
> Support additional policy directories

- qrexec/policy/parser.py
- qrexec/tests/qrexec_policy_daemon.py
- qrexec/tools/qrexec_policy_agent.py
- qrexec/tools/qrexec_policy_daemon.py
- qrexec/tools/qrexec_policy_exec.py
Convert to keyword-only arguments where it makes sense and disable
warning in other places.
> pylint: deal with too-many-positional-arguments

- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon-common.h
- daemon/qrexec-daemon.c
- libqrexec/ioall.c
- libqrexec/libqrexec-utils.h
- qrexec/policy/parser.py
- qrexec/tests/cli.py
- qrexec/tests/policy_graph.py
- qrexec/tests/policy_parser.py
- qrexec/tests/qrexec_legacy_convert.py
- qrexec/tests/socket/daemon.py
- qrexec/tests/socket/qrexec.py
- qrexec/tools/qrexec_policy_exec.py
- qrexec/tools/qrexec_policy_graph.py
- qrexec/utils.py
Open questions:
Fixes: QubesOS/qubes-issues#8510
> Implement UUID support in qrexec

- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon-common.h
- daemon/qrexec-daemon.c
- libqrexec/ioall.c
- libqrexec/libqrexec-utils.h
- qrexec/policy/parser.py
- qrexec/tests/cli.py
- qrexec/tests/policy_graph.py
- qrexec/tests/policy_parser.py
- qrexec/tests/qrexec_legacy_convert.py
- qrexec/tests/socket/daemon.py
- qrexec/tests/socket/qrexec.py
- qrexec/tools/qrexec_policy_exec.py
- qrexec/tools/qrexec_policy_graph.py
- qrexec/utils.py
This allows using UUIDs in qrexec policy, using the syntax uuid:VM_UUID.
This works anywhere a VM name is expected.  Since ':' is not allowed in
VM names, there is no ambiguity.  This requires the corresponding change
to qubes-core-admin so that qubesd supports UUIDs in the admin and
internal APIs.
Fixes: QubesOS/qubes-issues#8510
> Implement UUID support in qrexec (resolve conflict in #135)

- agent/qrexec-client-vm.c
- daemon/qrexec-client.c
Help is output to stderr at the moment
> Pipe `qrexec-client(-vm) --help` output to stdout

- rpm_spec/qubes-qrexec-vm.spec.in
Adjust according to https://fedoraproject.org/wiki/SELinux/IndependentPolicy#Creating_the_Spec_File
Specifically, when %selinux_relabel_post is used, %selinux_relabel_pre
needs to be there too.
QubesOS/qubes-issues#9663
> rpm: adjust SELinux snippets for relabeling

- daemon/qrexec-client.c
qrexec-client -d untrusted command
fails, but
qrexec-client -d untrusted user:command
works.
We could also mention that `DEFAULT` is accepted for user.
> docs: qrexec-client accepts user:command not command

- agent/qrexec-agent-data.c
- agent/qrexec-agent.c
- agent/qrexec-agent.h
- agent/qrexec-client-vm.c
- agent/qrexec-fork-server.c
- daemon/qrexec-client.c
- daemon/qrexec-daemon-common.c
- daemon/qrexec-daemon-common.h
- daemon/qrexec-daemon.c
- debian/control
- debian/libqrexec-utils2.install
- debian/libqrexec-utils2.shlibs
- debian/libqrexec-utils4.install
- debian/libqrexec-utils4.shlibs
- doc/execution.rst
- libqrexec/Makefile
- libqrexec/buffer.c
- libqrexec/exec.c
- libqrexec/libqrexec-utils.h
- libqrexec/open_logger.c
- libqrexec/process_io.c
- libqrexec/qrexec.h
- libqrexec/remote.c
- libqrexec/remote.h
- qrexec/client.py
- qrexec/tests/socket/agent.py
- qrexec/tests/socket/daemon.py
- selinux/qubes-core-qrexec.fc
Instead, directly execute the command from C.
The command’s environment inherits all environment variables from the
calling process _except_ for those that start with `QREXEC`.  Environment
variables that start with `QREXEC` are _not_ inherited, except for
`QREXEC_SERVICE_PATH` and `QREXEC_AGENT_PID`, but the following are set
explicitly:
- `QREXEC_SERVICE_FULL_NAME`
- `QREXEC_REMOTE_DOMAIN`
- `QREXEC_SERVICE_ARGUMENT` if the service argument is present and non-empty.
- `QREXEC_AGENT_PID` is set for calls to a VM that do not use `MSG_JUST_EXEC`.
Its handling in other cases is inconsistent, so such services should avoid it.
When the request is made to dom0, the following are also set:
- `QREXEC_REQUESTED_TARGET_TYPE` is set to `name` if the requested target does not start with
- …
> Stop using qubes-rpc-multiplexer

- daemon/qrexec-client.c
- libqrexec/buffer.c
- qrexec/client.py
- qrexec/tests/socket/agent.py
- qrexec/tests/socket/daemon.py
These are all minor fixes that can be backported.
> Small fixes

- agent/qrexec-fork-server.c
The process_io() (or more precisely - write_stdin() and write_all())
function relies on write() reporting errors "normally" (negative
return value + errno), it is not prepared to handle SIGPIPE signal. If
service exits, SIGPIPE sent to the qrexec-fork-server worker process
would kill it. The main qrexec-agent process correctly has SIGPIPE
handler set to SIG_IGN, but this was missing in qrexec-fork-server. Add
it there too.
This was found when debugging qrexec performance tests, but looks also
similar to this issue:
Fixes QubesOS/qubes-issues#5749
> Ignore SIGPIPE in qrexec-fork-server too

- agent/qrexec-agent.c
This is the convention used by the rest of qrexec.  This commit should be backported to stable branches.
> Use QREXEC_EXIT_PROBLEM for errors spawning child process

- agent/qrexec-agent.c
Previously 'qrexec-agent --fork-server-socket' (no argument) would segfault: it calls strdup() on optarg, but if there is no argument optarg is NULL.  This doesn't change behavior for any command lines that don't currently segfault, so it is safe to backport to R4.2.
Fixes: QubesOS/qubes-issues#9778
> qrexec-agent: Require an argument to --fork-server-socket

- agent/qrexec-agent.c
These should never happen, but call exit() if they do.  Also avoid freeing an uninitialized PAM handle in such an error case.
I do not consider this a security vulnerability because there is no reasonable way I know of for an attacker to trigger this failure, but this commit should still be backported.
> Fix checking for memory allocation errors

- rpm_spec/qubes-qrexec-vm.spec.in
It doesn't exist in F42 anymore, and appears to not really be needed.
QubesOS/qubes-issues#9807
> rpm: drop BR: lsb-core-noarch

- Makefile
- debian/qubes-core-qrexec.install
- libqrexec/qrexec.h
- rpm_spec/qubes-qrexec.spec.in
- selinux/qubes-core-qrexec.fc
- systemd/qrexec-volatile-config.conf
Originally, libqrexec only scanned /etc/qubes/rpc-config for RPC configuration. This prevented having truly ephemeral RPC config under /run/qubes/rpc-config, and also didn't allow local configuration to be stored under /usr/local/etc/qubes/rpc-config. Add both of these paths to QUBES_RPC_CONFIG_PATH.
/run/qubes/rpc-config needs some SELinux configuration for qrexec components to be able to access it, so add the needed config for that too.
Fixes https://github.com/QubesOS/qubes-issues/issues/9824
(Note, I'm not sure I did the `/run/qubes/rpc-config` directory creation correctly - I considered using `mkdir --parents` there, but was afraid of messing up the SELinux labeling on `/run/qubes` on accident by doing that. Instead, I opted to just make `/run/qubes/rpc-config`, allow the command to …
> Define additional default RPC config paths

- agent/qrexec-agent.c
- libqrexec/exec.c
Tests detect that sometimes qrexec call fails with QREXEC_EXIT_PROBLEM,
but no message about the actual cause. Review all instances of
QREXEC_EXIT_PROBLEM and try to cover missing ones with an error message.
> Add error messages to few more QREXEC_EXIT_PROBLEM cases

- qrexec/tests/policy_parser.py
- qrexec/utils.py
Converting UUIDs to names for ask targets was broken since it looked for '0123...' instead of 'uuid:0123...' in the system info.
Also adds text cases for this.
Fixes 578de5903316 ("Implement UUID support in qrexec")
> Fix uuid_to_name

- qrexec/tools/qrexec_policy_agent.py
Gtk docs suggest set_icon_from_icon_name as replacement. But for some reason that uses another theme. So instead reuse the code from the fallback in _get_icon.
> qrexec-policy-agent: Replace usage of deprecated Gtk.Entry.set_icon_from_stock

- qrexec/tests/socket/daemon.py
Don't close server before source. Otherwise the read to source can fail with "Broken pipe".
---
That is unless I misunderstood the intended behavior in this test case. In that case the implementation needs to be fixed.
> Fix TestClient::test_run_dom0_service_socket_no_read

- Makefile
- debian/rules
- rpm_spec/qubes-qrexec-dom0.spec.in
- rpm_spec/qubes-qrexec-vm.spec.in
Agent restart is supported since 4.1.0 version, do restart it on update.
This avoids compatibility issues when qrexec-client-vm version is newer
than qrexec-agent itself.
> Restart qrexec-agent on update

- archlinux/PKGBUILD.in
- debian/control
- qrexec/tools/qrexec_policy_agent.py
- rpm_spec/qubes-qrexec.spec.in
Glib >= 3.50 has native asyncio integration. When available, use it
instead of gbulb.
This requires few minor changes:
- asyncio.run() doesn't work there (asyncio.set_event_loop() cannot be
called on the main thread with glib...)
- there is no gbulb.wait_signal() anymore - implement it manually
Based on https://github.com/QubesOS/qubes-core-qrexec/pull/191 by
@CertainLach
QubesOS/qubes-issues#9809
> Use glib's native asyncio integration when available

- agent/qrexec-agent.c
- selinux/qubes-core-qrexec.te
When qrexec-agent restarts, it needs to remove the old socket file before
creating the new one. Let the agent do that when SELinux is enabled.
Fixes QubesOS/qubes-issues#9982
And also, remove the socket on shutdown too.
> selinux: fix qrexec-agent restart

- qrexec/policy/parser.py
- qrexec/tests/policy_parser.py
Instead of denying the call with confusing assert, log a warning
explaining the situation but still display the ask prompt, just without
the default target selected. In some (many?) cases, the intention of
default_target= was to have a prompt just to confirm the operation, not
actual target selection - and in those cases, the intended operation
still won't succeed (as the intended target is not allowed). But in some
cases, user may still want choose an alternative target (for example
after renaming a qube)
QubesOS/qubes-issues#9980
> policy: ignore (with warning) non-allowed default_target=

- qrexec/policy/parser.py
Warn only if default_target is already set. If it's None already, there
is no reason for warning about setting it (again) to None.
And fix a typo in the message.
Reported at https://github.com/QubesOS/qubes-mgmt-salt-dom0-virtual-machines/pull/75
> Fix warning about wrong default_target

- rpm_spec/qubes-qrexec-vm.spec.in
Do not fail the RPM transaction if not running installation under
systemd. This specifically applies to containers (CI) and template build
(chroot). While theoretically post-trans scriptlet failure is not fatal,
in practice rpm in Fedora 43 does consider such transaction failed.
QubesOS/qubes-issues#10102
> rpm: don't fail posttrans scriptlet when running in chroot/container
